apiVersion: v1
kind: Pod
metadata:
  name: myapp
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    command: ["sleep","3600"]
    ports:
    - containerPort: 8080
    resources:
      requests:
        memory: "1Gi"
        cpu: 1
      limits:
        memory: "2Gi"
        cpu: 2


# 1 G (Gigabyte) = 1,000,000,000 bytes
# 1 M (Megabyte) = 1,000,000 bytes
# 1 K (Kilobyte) = 1,000 bytes

# 1 Gi (Gibibyte) = 1,073,741,824 bytes
# 1 Mi (Mebibyte) = 1,048,576 bytes
# 1 Ki (Kibibyte) = 1,024 bytes

# By default kubernetes limits 1vCPU and 512Mi per pod

# 0.1vCPU = 100m (milli)
# 1m - lowest cpu limit

# CPU throttles when over the limit
# MEMORY call exceed limit but pod will be terminated after too much time exceeding limit

# OOMKilled - status ran out of memory
